export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_FETCH = 'USER_FETCH';
export const USER_LOADING = 'USER_LOADING';
export const USER_ADD = 'USER_ADD';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_DETAILS_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_OTP_VALIDATION = 'USER_OTP_VALIDATION';
export const USER_FAILED = 'USER_FAILED';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const GET_OTP_REQUEST_ID = 'GET_OTP_REQUEST_ID';
export const GET_OTP_VALIDATE = 'GET_OTP_VALIDATE';



